name: Publish

on:
  pull_request:
    branches: [master]
    types: [closed]

permissions:
  contents: read
  pull-requests: read

env:
  DOTNET_VERSION: 8.0.*
  SOLUTION_FILE: Mediator.Lite.sln
  PROJECT_PATH: ./src/Mediator.Lite/Mediator.Lite.csproj
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build
        run: |
          dotnet build ${{ env.SOLUTION_FILE }} \
            --configuration Release \
            --no-restore

      - name: Test
        run: |
          dotnet test ${{ env.SOLUTION_FILE }} \
            --configuration Release \
            --no-build \
            --no-restore \
            --verbosity normal

      - name: Pack
        run: |
          mkdir nupkgs
          dotnet pack ${{ env.PROJECT_PATH }} \
            --configuration Release \
            --no-build \
            --output ./nupkgs
    
      - name: Push
        run: |
          dotnet nuget push "./nupkgs/*.nupkg" \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json